# Generated by Django 5.2.16 on 2026-07-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Internship', 'Internship')], max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('posted_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
