# Generated by Django 5.2.16 on 2026-07-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('client', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('short_description', models.CharField(max_length=250)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('result', models.TextField()),
                ('tools', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
